/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { THREE } from "enable3d";
import { useFrame } from '@react-three/fiber'
import { a, useSpring } from "@react-spring/three";

export default function Model(props) {
  const group = useRef()
  const [active, setActive] = useState(false)
  const [hovered, setHover] = useState(false)
  const [reset, setReset] = useState(false)

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, Math.cos(t / 8) / 20, 0.1)
    group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, Math.sin(t / 8) / 20, 0.1)
    group.current.rotation.z = THREE.MathUtils.lerp(group.current.rotation.z, Math.sin(t / 8) / 40, 0.1)
  })

  const { color, rotation, position } = useSpring({
    position: props.active ? [3.5, 1.4, 2.5] : [3.5, 5, 2.5],
    rotation: active ? [1.58, 0, Math.PI] : [1.58, 0, -Math.PI],
    color: active ? props.mainColor : 'white',
    config: { mass: 10, tension: 1000, friction: 300, precision: 0.00001 },
    reset: true
  })

  const { nodes, materials } = useGLTF('/aboutme.glb')
  return (
    <group ref={group} dispose={null}>
      <a.mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.004']}
        mass={1}
        // position={[3.5, 1.4, 2.5]}
        position={position}
        rotation={rotation}
        onClick={e => setActive(!active)}
        scale={[0.75, 0.1, 0.75]}
        receiveShadow={props.active}
        castShadow={props.active}
        onPointerOver={(e) => setHover(true)}
        onPointerOut={(e) => setHover(false)}
        >
          <a.meshStandardMaterial attach="material" color={color} />
        </a.mesh>
    </group>
  )
}

useGLTF.preload('/aboutme.glb')
