/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { THREE } from "enable3d";
import { useFrame } from '@react-three/fiber'
import { a, useSpring } from "@react-spring/three";

export default function Model(props) {
  const group = useRef()
  const [active, setActive] = useState(false)
  const [hovered, setHover] = useState(false)
  const [reset, setReset] = useState(false)

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    // group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, Math.cos(t / 8) / 20, 0.1)
    // group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, Math.sin(t / 8) / 20, 0.1)
    // group.current.rotation.z = THREE.MathUtils.lerp(group.current.rotation.z, Math.sin(t / 8) / 40, 0.1)
  })

  const { color, rotation, subColor, position } = useSpring({
    position: props.active ? [4, 1.4, 3.2] : [4, 5, 3.2],
    rotation: active ? [0, Math.PI, 0] : [0, -Math.PI, 0],
    color: active ? props.mainColor : 'grey',
    subColor: active ? props.subColor : 'grey',
    config: { mass: 10, tension: 1000, friction: 300, precision: 0.00001 },
    reset: true
  })

  const { nodes, materials } = useGLTF('/work.glb')
  return (
    <group ref={group} dispose={null}>
      <a.group scale={[0.34, 0.01, 0.30]} 
          position={position} 
          rotation={rotation} 
          receiveShadow 
          castShadow 
          onPointerOver={(e) => setHover(true)}
          onPointerOut={(e) => setHover(false)}
          onClick={e => setActive(!active)}
          color={color}
          receiveShadow={props.active}
          castShadow={props.active}
      >
        <a.mesh geometry={nodes.Cube005.geometry} material={materials['Material.043']}> <a.meshStandardMaterial attach="material" color={color} /> </a.mesh>
        <a.mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.044']}> <a.meshStandardMaterial attach="material" color={color} /> </a.mesh>
        <a.mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.008']}> <a.meshStandardMaterial attach="material" color={color} /> </a.mesh>
        <a.mesh geometry={nodes.Cube005_3.geometry} material={materials['Material.040']}> <a.meshStandardMaterial attach="material" color={color} /> </a.mesh>
        <a.mesh geometry={nodes.Cube005_4.geometry} material={materials['Material.041']}> <a.meshStandardMaterial attach="material" color={color} /> </a.mesh>
        <a.mesh geometry={nodes.Cube005_5.geometry} material={materials.Material} />
        <a.mesh geometry={nodes.Cube005_6.geometry} material={materials['Material.002']}> <a.meshStandardMaterial attach="material" color={'black'} /> </a.mesh>
        <a.mesh geometry={nodes.Cube005_7.geometry} material={materials['Material.003']}> <a.meshStandardMaterial attach="material" color={'black'} /> </a.mesh>
        <a.mesh geometry={nodes.Cube005_8.geometry} material={materials['Material.001']}> <a.meshStandardMaterial attach="material" color={'black'} /> </a.mesh>
        <a.mesh geometry={nodes.Cube005_9.geometry} material={materials['Material.036']}> <a.meshStandardMaterial attach="material" color={'black'} /> </a.mesh>
      </a.group>
    </group>
  )
}

useGLTF.preload('/work.glb')
